apiVersion: v1
data:
    password: ENC[AES256_GCM,data:nZcWp2mHF1k=,iv:X4JRs0BlvYkQAMVBPh+NuKgXWS3LuKqK2OgI2B+fzM0=,tag:2QiZk0uyxxTWJXxt+OXgBA==,type:str]
    user: ENC[AES256_GCM,data:4wetXP0LB0c=,iv:J8RulCVJ4lxouKLoXW9XDAINmf94iaCj7FTJgD3hi5E=,tag:TLFiRo+G+4RejqWNxyhuQA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1ulhml2yr47jn9mpway37m34chmd70yamj8ecyy4njc85mncx6qesfrgzva
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeUxwNE9SSE1YVm5sQjlB
            R2RBKzhwaHoyTlVMcFZzdzRoUXNKdDA3Qnk0CnVlRzNGVW8raE5MTHBJWHlPd0Qz
            MDR3bWJEZ1NvbUxHZmR2Q3drS0FTS3MKLS0tIDd0OGd1ZlEwUkhRMWo2a280czNw
            TFlCNmdlUkg5OVhNSXZhZWErUlVhL2sKy5066OzQA7yNQ4BRuTvvIHXOJlC8vRyB
            GLVB/oDU2yT9pL096u05CYTTOOBh482l9nKMsrOpKmf2TlSjfrym5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T02:16:16Z"
    mac: ENC[AES256_GCM,data:+CL6giYQ8AeMwL4+z8w689vgBVd5SUUSlzx0qOy2eyVW732U8bHKisy4TMR9JwXo0stFEhftgwN0EGAqHkEmG/PddK3nz2nLe0ZaeTdSSGYVNp75rzFJV1SHeIoi7dDWi7xS8yLQXomIjt4MII8UoOpBMof7bpK1W2LCBLEKJaI=,iv:h74f4JejMDQyXG+cgF9tgtta4dlipPeJYvDCySQVRlo=,tag:FZ/JSaHNAbCSO1Cu+LIXEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
