apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:irA0yKk++J1MwgBtkaDWedhjQZO8h6y7/YmsCznehabSeV68hiDd31h4Gi2psg3/n5uCTjh2wOrS/unbrRoWsw1G3DGpkFBKxSMSOGKBNX3Y0jyAJgwZ8WXs+hTd9ke+Z4MAKM25/Pl54prpyXYN6vpRan1HDZ2WdUcES5pUuMSbgdqsEQkfD2ArUGrStjmTjZbVzBgkaIE7Moo42ZVinSqcjfhEbbBAKE2iOAJsSeNIeP9W6X13Aa+rMxn6GUPVRIntuFvm8FWkkuMNzBoUfYdI0QcdrueO8WXOSQglpOwL2wQ+JntajRH+Jtg=,iv:+vuhQuKXcSBFGSlosgl5KWA1kiJECH3R/I4yd6HohZ0=,tag:BYWvsgYzt4q/MwLuZwr+ZA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1qqlk7juwa7yfjjqfkhwdv7h9m0eswzasx9sl6nyu84nevq62aczs6dn3mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNDkxUjFzTkEwS2QrNW9N
            cmo4ajl0UE5Ra0U5TGIrNzBvZU1iZG5mOEFFCm1sbUVOcGhGWmVZMzBsNUZHTjJH
            ZFE3dmovVFJSNEJrRmRHR3pSaG9KVUkKLS0tIDFxRUJ3YW9OQjl2RnQxZ1ZYRG1a
            V3VqWmFIeGdlcEVxSmRTN01KYnZiOUkKvf6xp/SgdoruqHoot6N7M0Rjlx1SEVih
            CL+57+BMyLzzfIUFFSS44IjKKxejwc+Sl2BStnlJHbDdzdO1b8yfgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T20:40:09Z"
    mac: ENC[AES256_GCM,data:37Gnkd1ivYfHg5YOXbGhVklKjlAaf6kQwFzxMGhKIQkb/ifEYPh2MIIfuUEdlF34lLsw+6nS9lqyxRzhHuYqfEopUcZpWbDfKgiyYgVhwNiu8cfAWZRgm5n/Z6rCr4ksgekYegdRTZO9bfA7ZOyh6jKd8Hh7gfl9cvHVPqUxrns=,iv://pKFAVkKnFJa8bjGS7Bd5P0cgN8U0WfLnjOKiTciP0=,tag:WrtHXhxG5ZWViwfFReVWBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
