apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:GeMZva/ncNcCX5e/,iv:o1cW6XKOI5kUp6UnelUHaD3DrOF70EcRtMJriMjux+o=,tag:APP783ep1uLlzcVkIzC1IA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ioUKDOUvIpPhGfO5,iv:LqwmJ5KNWuslvr9L/GZXxso9JKauKCMwTxYFtRoIuMo=,tag:76VTXojoieP8TT551bR8YA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1qqlk7juwa7yfjjqfkhwdv7h9m0eswzasx9sl6nyu84nevq62aczs6dn3mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkVlS1B0QTBtQ0NDL3FD
            WE1ud0VvRGpJam42dEFNQ2prU2dXbUtya3dFCjJJdVIyZ1J0M1ZRTmMvYnhGQmhJ
            a2lMNVZ5ajBxTXI4djR3K3B3WHZ3SFUKLS0tIENOK3ZuWm9keFp1cTdBODFNM3BR
            ZmY2Qm9MT3ZhZFdFZjRReThmOWF0ZkkKknmksiIpRhv4nzc+t+wM5xfImTmv1K4+
            /91PA0Sk6GgivJxZ+21EhvngUhSeB93fEe0TNWXFnLEnpBGdyvx3EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T01:52:14Z"
    mac: ENC[AES256_GCM,data:ySRO58qL103lpS8TzQq+pHyOJvC07NsiLZ25PjGMQR5CpTCGqS5Mi0ctPIQp5yg6gpKN0p3b0xvpJqGZGxFgeo0fCMDbNBLa0mCywy14iUWcwCyN9clE9ze/Xr1iI0wf0dhMUENKdWjC7ndmTv16H/evRoX7MKUD5xUHklBeM+U=,iv:osMxlF91ZkIjIhW5Q2pHJGE1AbVh33m8xYuGCm9Bi9w=,tag:Uwh8ZBmVfopnf/TWpXHuEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
