apiVersion: v1
data:
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:P2OwuuuwcIkuX/bUgs3wPw==,iv:i+o4eLqFewKXaRnicTB/Gt1laCXvwuzSO/jfNPLc/Xg=,tag:Nfz2xYG/3Syr902v9JRGFQ==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:ZYXk1zmS7E5ctv4a,iv:PVt+d5jf+KQ5dEUPA+VrSSzbbZQLirCX6yAh/NEtFMo=,tag:uvRGcJzWYA25rLTqrHDuog==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1qqlk7juwa7yfjjqfkhwdv7h9m0eswzasx9sl6nyu84nevq62aczs6dn3mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdFhQUHk5MHdvU3B5SzJZ
            V3ZkL3NmR2NJSGk3Rk5ETWlOay9wcEZPelIwClArREJ2UnRsZTdVVFFDSmpuc2FL
            bUN1Vi9CbUIzMmtTTDN4RDIvWDN2dFEKLS0tIDBWU045Rm5Ea3VpWU5EZ1A4QXIx
            STViSlcrMGUvYTdXZWlVTmk3RHUxblUKDCmbFH12XqOhd6mnwh+Sh0CemGme8UYj
            8puImIGXazr+891y9+3kzM8aA9QSoF6hwSbR9ngAXeWpn5FCHYLCVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T20:49:08Z"
    mac: ENC[AES256_GCM,data:qTCvwnovJHNkK0ZaLkOIf63R0AJBi3RcjLs6F48nVUzw0N7qUiz890bjmPVyvuuWjiX7LRHAoSbwGbdU5RgAxmIvZhYj6OmFkXllgVYTHe/CGfaEM1FP9TQm43AJ2esAlJFg9CgJZ/7/a4eLoZRZJ4YtuLmjvdCN7yvpe5hkKf0=,iv:wnWiVSDhE023KNFpW93EFegrxBGIOQV6JyzicbgcMpA=,tag:iFrQNuyPBWmX33RBFBwzNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
