apiVersion: v1
data:
    password: ENC[AES256_GCM,data:X0owBjoz7pk=,iv:jDIxROKmM1dsD3fo1HDsHoQlywi2wMY2+ebRT/FMIbw=,tag:NEeKQ4Paqo6VKzQ6vf7Bgw==,type:str]
    user: ENC[AES256_GCM,data:sIKld2evCmc=,iv:lXFLZlM7392f/0j2y153U3PnziG9izIzuXAlIwj8Gg8=,tag:N+eXTe6PnG0e/4llCcgUsQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1qqlk7juwa7yfjjqfkhwdv7h9m0eswzasx9sl6nyu84nevq62aczs6dn3mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaWFkeWJQbVpIL1Z3WXFh
            d0JpcnFoZWhJTlB3Sm1ld3NvTWlUbFBnSmo4CnpQeFVKNkRQUlkxZU8yTWM2ckIy
            MmJscFpjVDk0QytqU2s5eTZMUFdpUmcKLS0tIGRzYmNuNDZuWUNpb2ZWK3ltTlc1
            QlNXcldNT3F3V2JNSzRHUUtwZ0VPblUKWB9nSZP7KZ5lL//KZA61Xf+5QoxgIEGY
            pPK045a/lrlm2PMrKIvaThNp8tithdiuQELiWMZOdt+StSlv5sGktQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T18:33:59Z"
    mac: ENC[AES256_GCM,data:5ZoJ5fRvdBTsflgAbrSG3L5ZM4DNKbYLJwcv7DpPrEQ9HQ6hSGCRYkRS1TwSuwBWQAgdh8kF9A/1Q8BtjNfSNY4ySEf7UsBmqDMsm1QWemqJ/ThbCwVX+2AtqWGvYkqp4uFO5U4o7L+sOZARTBKgo2SCB23LDoHJdlaF+cXUHrs=,iv:wKRVhpRY7wiyTCcYva0xxSg37qQmx2GZGyxdOt7QmjU=,tag:AuLK8z7crIJttGX55RjxXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
