apiVersion: v1
data:
    password: ENC[AES256_GCM,data:H+H2hQCY47A=,iv:EpZUm7el/eFsMTxwU8gxZYPW+pXs4J74GzLbsI+ZTeo=,tag:dhvxkmdF6oJTBqxVPYq4Hg==,type:str]
    user: ENC[AES256_GCM,data:2Jhs5DWrpAU=,iv:40xWywy7FqpTEnw6pUjo5er3vqKpTqIhmF+4DlsHTyU=,tag:fbGOMWdLmG/wJe2bjkBfLA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1w79vknzafds96z4mtch38q5rq9x254v2n0s3ej2up7mh7d7ffq9sl3czrv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z2VlcGd5bEs0NEY0QnZh
            bjM3ZUo2RktNdTRaWUdLVGZnbWpCZlRKbzNJCmJXeUJpYmw5RnVFSTdlb1dNaVNG
            K05XM1lFeEFuSFdCb2RPOW9LTVFvSVUKLS0tIGY2blRSVnVNcEpHb3dDcVVCNVZ4
            RUVkVjRmMmxSaVVMYVBHS1dKOEN2WEEKFExagrDIdf4WvlnBxod2a1dFKvZ6VmL5
            003fksbLMbGek+syrXlUwO8rmutWjCqlYo7GBg2sJaQmahZp233lvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:53Z"
    mac: ENC[AES256_GCM,data:VLfoGzlFEWQITXQMfq9vNPRvBXh1YMKDPDvp3PFGXKYN3JqN5H3uHzNXm8LkIzZZySrjNrzFezymIh1lXOz/QOOCMv2PVIDFGicDG65zjixxkyaCAEX1tFzJgZoY1sDFCklZyKgUWpVROXwLrgzzga3zmQd/JInzlN7+e/ljWug=,iv:GTV5SuvjS8YADIVePcaDwPPdxFCYvR9TrKGKpU86/4Y=,tag:1zk1q4eTRIsAsKOH5IfYKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
