apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Mq3siPn/E0N6PfMv,iv:bAQ8SByP70x/0Es9CKZgm4yARM9lEqVifOI0gGtsz1k=,tag:xaMt/xA3o/CK+1gezNEWgQ==,type:str]
    admin-user: ENC[AES256_GCM,data:faUSIvSQCvE=,iv:+9fa4cyMnmZI5sogiDwf5iq6LuTga3ZB17ecWQrz8+w=,tag:V71GjctAxdzqxc6v/rw8uA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
sops:
    age:
        - recipient: age1qqlk7juwa7yfjjqfkhwdv7h9m0eswzasx9sl6nyu84nevq62aczs6dn3mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ukd0L1p5UjZhRWVJTURh
            WHRQV3UvOWlRR3ZpV0tUaTRTNW0xSVRGSlFjCnBET085clhGSzU0TStUT1lRMitL
            dlNUTDNqclJhQlZsYzdYZkhGT1J5NmsKLS0tIGxTRWZ1alN0SE5nRUVUWXlrblVN
            Y1cvVDdTTllYeEoxbkNObnQrREN0b0kKEIJQgeCTd5q2LLS2VdsYeMPbqneynXyh
            3hBj4QftdxofH3gjqxFyU/lOZMyv2MBityutiUR/wYOKZEtGOjsAww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T21:18:23Z"
    mac: ENC[AES256_GCM,data:dSoT/JnV7xoWrABnCjzzXjMEdOaWGivqGwiqQ66yxlSxWpe6eIXwQwYdWhQBvG09Go4rCs9c17lRHpQW5RVD3c7XSael3+0SxVloFmhNUwGvu5OEES7f89OhjKwp0zT52Lq76L4K4QOnVLi30AkIbwKSIDrt4+SbvAsJTGsI/sU=,iv:iml/UiPH/sKfXDiOxRo/PDz3+VSNqpGHuZmoUOKk1dI=,tag:BnroFEcSj9ZuS2he4o1Vog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
